FROM php:8.2-fpm-alpine as webserver

WORKDIR /var/www/html/

# Essentials
RUN addgroup -g 1000 -S www-data \
    && adduser -u 1000 -D -S -G www-data www-data
RUN apk update && apk upgrade && apk add --no-cache zip unzip curl sqlite nginx supervisor bash nodejs npm

# Enable extension
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions; \
    install-php-extensions zip gd pdo_mysql

RUN rm /var/cache/apk/*

# Configure supervisor
RUN mkdir -p /etc/supervisor.d/
COPY .docker/config/supervisor.ini /etc/supervisor.d/supervisord.ini

# Configure nginx
COPY .docker/config/nginx.conf /etc/nginx/
COPY .docker/config/laravel.conf /etc/nginx/http.d/default.conf
RUN nginx -t

RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

# Configure PHP FPM
COPY .docker/config/php.ini /var/local/etc/php
COPY .docker/config/php-fpm.conf /var/local/etc

EXPOSE 80

CMD ["supervisord", "-c", "/etc/supervisor.d/supervisord.ini"]
