services:

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'laravel'
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - tarot

  app:
    build:
      context: ../.
      dockerfile: Dockerfile.prod
    image: tarotapp
    environment:
      - APP_URL=http://localhost
      - APP_DEBUG=false
      # - DB_CONNECTION=mysql
      # - DB_HOST=mysql
      # - DB_PORT=3306
      # - DB_DATABASE=admin_tarot
      # - DB_USERNAME=appkey
      # - DB_PASSWORD=diablo
    ports:
      - 9001:80
    volumes:
      - "../storage:/var/www/html/storage"
    networks:
      - tarot
    depends_on:
      - mysql

networks:
  tarot:
    driver: bridge
