services:

  fpm:
    build:
      context: ./
      dockerfile: fpm.dockerfile
    working_dir: /var/www/html
    volumes:
      - ../.:/var/www/html
    environment:
      - DB_PORT=3306
      - DB_HOST=database
    networks:
      - laravel_app
    depends_on:
      - database
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    working_dir: /var/www/html
    volumes_from:
      - fpm
    networks:
      - laravel_app
    ports:
      - 9001:80

  database:
    image: mysql:8
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'admin_app'
      MYSQL_USER: 'appkey'
      MYSQL_PASSWORD: 'appkey'
      MYSQL_ROOT_PASSWORD: 'appkey'
      MYSQL_ROOT_HOST: '%'
    networks:
      - laravel_app

networks:
  laravel_app:
    driver: bridge

volumes:
  dbdata:
