version: '3'

services:

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: diablo

  app:
    image: .
    environment:
      - APP_URL=http://localhost
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=admin_tarot
      - DB_USERNAME=root
      - DB_PASSWORD=diablo
    ports:
      - 9001:9000
      