services:

  fpm:
    build:
      context: ./
      dockerfile: fpm.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    working_dir: /var/www/html
    volumes:
      - ../.:/var/www/html:rw
    environment:
      - DB_PORT=3306
      - DB_HOST=database
    networks:
      - laravel_app
    depends_on:
      - database
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    working_dir: /var/www/html
    volumes_from:
      - fpm
    networks:
      - laravel_app
    ports:
      - 9001:80
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 128M
  database:
    image: mysql:8
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'admin_app'
      MYSQL_USER: 'appkey'
      MYSQL_PASSWORD: 'appkey'
      MYSQL_ROOT_PASSWORD: 'appkey'
      MYSQL_ROOT_HOST: '%'
    networks:
      - laravel_app
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 412M
  adminer:
    image: adminer
    restart: always
    ports:
      - 8091:8080
    networks:
      - laravel_app

networks:
  laravel_app:
    driver: bridge

volumes:
  dbdata:
